"
I represent a node in the ROS system.
"
Class {
	#name : #PDNode,
	#superclass : #Object,
	#category : #'PhaROSDashBoard-Model'
}

{ #category : #public }
PDNode >> info [

	self shouldBeImplemented.
]

{ #category : #public }
PDNode >> isAlive [

	self shouldBeImplemented.
]

{ #category : #public }
PDNode >> kill [

	self shouldBeImplemented.
]

{ #category : #public }
PDNode >> ping [

	self shouldBeImplemented.
]

{ #category : #public }
PDNode >> topics [

	self shouldBeImplemented.
]
