Class {
	#name : #ActionlibTestRequestFeedback,
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> rosTypeName [ 
^'actionlib/TestRequestFeedback'
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> typeCreationOrder [ 
^14
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback >> initialize [
	super initialize.

]
