Class {
	#name : #ActionlibTwoIntsFeedback,
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> rosTypeName [ 
^'actionlib/TwoIntsFeedback'
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> typeCreationOrder [ 
^21
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback >> initialize [
	super initialize.

]
