Class {
	#name : #ActionlibTwoIntsFeedback,
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback class >> rosTypeName [ 
^'actionlib/TwoIntsFeedback'
]

{ #category : #'as yet unclassified' }
ActionlibTwoIntsFeedback >> initialize [
	super initialize.

]
