Class {
	#name : #ActionlibTestRequestFeedback,
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback class >> rosTypeName [ 
^'actionlib/TestRequestFeedback'
]

{ #category : #'as yet unclassified' }
ActionlibTestRequestFeedback >> initialize [
	super initialize.

]
