Class {
	#name : #'Control_msgsPointHeadResult',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Control_msgsPointHeadResult class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Control_msgsPointHeadResult class >> rosTypeName [ 
^'control_msgs/PointHeadResult'
]

{ #category : #'as yet unclassified' }
Control_msgsPointHeadResult >> initialize [
	super initialize.

]
