Class {
	#name : #'Gateway_msgsConnectionType',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> action_client [
	^'action_client'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> action_server [
	^'action_server'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> invalid [
	^'invalid'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> publisher [
	^'publisher'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> service [
	^'service'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType class >> subscriber [
	^'subscriber'

]

{ #category : #'as yet unclassified' }
Gateway_msgsConnectionType >> initialize [
	super initialize.

]
