Class {
	#name : #'Move_base_msgsMoveBaseResult',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Move_base_msgsMoveBaseResult class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
Move_base_msgsMoveBaseResult class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Move_base_msgsMoveBaseResult class >> rosTypeName [ 
^'move_base_msgs/MoveBaseResult'
]

{ #category : #'as yet unclassified' }
Move_base_msgsMoveBaseResult >> initialize [
	super initialize.

]
