Class {
	#name : #'Nav_msgsGetMapFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Nav_msgsGetMapFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Nav_msgsGetMapFeedback class >> rosTypeName [ 
^'nav_msgs/GetMapFeedback'
]

{ #category : #'as yet unclassified' }
Nav_msgsGetMapFeedback >> initialize [
	super initialize.

]
