Class {
	#name : #'Nav_msgsGetMapGoal',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Nav_msgsGetMapGoal class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Nav_msgsGetMapGoal class >> rosTypeName [ 
^'nav_msgs/GetMapGoal'
]

{ #category : #'as yet unclassified' }
Nav_msgsGetMapGoal >> initialize [
	super initialize.

]
