Class {
	#name : #'Rocon_interaction_msgsStrings',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Rocon_interaction_msgsStrings class >> remocons_namespace [
	^'/remocons'

]

{ #category : #'as yet unclassified' }
Rocon_interaction_msgsStrings class >> rosTypeDefinition [ 
^' string REMOCONS_NAMESPACE=''/remocons''
'
]

{ #category : #'as yet unclassified' }
Rocon_interaction_msgsStrings class >> rosTypeName [ 
^'rocon_interaction_msgs/Strings'
]

{ #category : #'as yet unclassified' }
Rocon_interaction_msgsStrings >> initialize [
	super initialize.

]
