Class {
	#name : #'Rocon_app_manager_msgsConstants',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> no_remote_connection [
	^'none'

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> no_remote_controller [
	^'none'

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants >> initialize [
	super initialize.

]
