Class {
	#name : #'Rocon_app_manager_msgsConstants',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> no_remote_connection [
	^'none'

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> no_remote_controller [
	^'none'

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> rosMd5Sum [ 
^'8dc55825f8d5b0d293568ddca66ef50f'
]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> rosTypeDefinition [ 
^' string NO_REMOTE_CONNECTION=''none''
 string NO_REMOTE_CONTROLLER=''none''
'
]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> rosTypeName [ 
^'rocon_app_manager_msgs/Constants'
]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants class >> typeCreationOrder [ 
^213
]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsConstants >> initialize [
	super initialize.

]
