Class {
	#name : #'Rocon_std_msgsStrings',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_groovy [
	^'groovy'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_hydro [
	^'hydro'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_indigo [
	^'indigo'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_opros [
	^'opros'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_other [
	^'application_framework_other'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> application_framework_ros_other [
	^'ros_other'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_galaxy [
	^'galaxy'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_mega [
	^'mega'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_note10 [
	^'note10'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_note3 [
	^'note3'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_pc [
	^'pc'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_phone_other [
	^'phone_other'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_pr2 [
	^'pr2'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_robot_other [
	^'robot_other'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_tablet_other [
	^'tablet_other'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_turtlebot2 [
	^'turtlebot2'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_waiterbot [
	^'waiterbot'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> hw_xoom [
	^'xoom'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_arch [
	^'arch'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_chrome [
	^'chrome'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_debian [
	^'debian'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_fedora [
	^'fedora'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_firefox [
	^'firefox'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_freebsd [
	^'freebsd'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_gentoo [
	^'gentoo'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_honeycomb [
	^'honeycomb'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_ice_cream_sandwich [
	^'ice_cream_sandwich'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_internet_explorer [
	^'internet_explorer'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_jellybean [
	^'jellybean'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_kitkat [
	^'kitkat'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_opera [
	^'opera'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_osx [
	^'osx'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_precise [
	^'precise'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_quantal [
	^'quantal'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_raring [
	^'raring'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_safari [
	^'safari'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_saucy [
	^'saucy'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_windows7 [
	^'windows7'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> os_winxp [
	^'winxp'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> rocon_version [
	^'acdc'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> tag_gazebo_robot_type [
	^'concert_gazebo'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> tag_rapp [
	^'rocon_app'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> tag_service [
	^'concert_service'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> tag_software [
	^'software_farm'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings class >> uri_wildcard [
	^'*'

]

{ #category : #'as yet unclassified' }
Rocon_std_msgsStrings >> initialize [
	super initialize.

]
