Class {
	#name : #'Rocon_app_manager_msgsErrorCodes',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> already_remote_controlled [
	^32

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> client_connection_disrupted [
	^36

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> inviting_controller_blacklisted [
	^35

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> inviting_controller_not_whitelisted [
	^34

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> local_invitations_only [
	^30

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> multi_rapp_not_supported [
	^10

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> no_local_gateway [
	^31

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> not_current_remote_controller [
	^33

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> rapp_is_not_available [
	^21

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> rapp_is_not_running [
	^20

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> success [
	^0

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes class >> unknown [
	^1

]

{ #category : #'as yet unclassified' }
Rocon_app_manager_msgsErrorCodes >> initialize [
	super initialize.

]
