Class {
	#name : #'Stdr_msgsDeleteRobotFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> rosTypeName [ 
^'stdr_msgs/DeleteRobotFeedback'
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> typeCreationOrder [ 
^328
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback >> initialize [
	super initialize.

]
