Class {
	#name : #'Stdr_msgsSpawnRobotFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Stdr_msgsSpawnRobotFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Stdr_msgsSpawnRobotFeedback class >> rosTypeName [ 
^'stdr_msgs/SpawnRobotFeedback'
]

{ #category : #'as yet unclassified' }
Stdr_msgsSpawnRobotFeedback >> initialize [
	super initialize.

]
