Class {
	#name : #'Stdr_msgsRegisterRobotFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Stdr_msgsRegisterRobotFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Stdr_msgsRegisterRobotFeedback class >> rosTypeName [ 
^'stdr_msgs/RegisterRobotFeedback'
]

{ #category : #'as yet unclassified' }
Stdr_msgsRegisterRobotFeedback >> initialize [
	super initialize.

]
