Class {
	#name : #'Stdr_msgsDeleteRobotFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback class >> rosTypeName [ 
^'stdr_msgs/DeleteRobotFeedback'
]

{ #category : #'as yet unclassified' }
Stdr_msgsDeleteRobotFeedback >> initialize [
	super initialize.

]
