Class {
	#name : #'Tf2_msgsLookupTransformFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> rosTypeName [ 
^'tf2_msgs/LookupTransformFeedback'
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback >> initialize [
	super initialize.

]
