Class {
	#name : #'Tf2_msgsLookupTransformFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> rosTypeName [ 
^'tf2_msgs/LookupTransformFeedback'
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback class >> typeCreationOrder [ 
^372
]

{ #category : #'as yet unclassified' }
Tf2_msgsLookupTransformFeedback >> initialize [
	super initialize.

]
