Class {
	#name : #'Turtle_actionlibShapeFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Turtle_actionlibShapeFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Turtle_actionlibShapeFeedback class >> rosTypeName [ 
^'turtle_actionlib/ShapeFeedback'
]

{ #category : #'as yet unclassified' }
Turtle_actionlibShapeFeedback >> initialize [
	super initialize.

]
