Class {
	#name : #'Turtlebot_actionsFindFiducialFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> rosTypeName [ 
^'turtlebot_actions/FindFiducialFeedback'
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback >> initialize [
	super initialize.

]
