Class {
	#name : #'Turtlebot_actionsFindFiducialFeedback',
	#superclass : #PhaROSValue,
	#category : #PhaROSGenerated
}

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> rosMd5Sum [ 
^'d41d8cd98f00b204e9800998ecf8427e'
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> rosTypeDefinition [ 
^''
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> rosTypeName [ 
^'turtlebot_actions/FindFiducialFeedback'
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback class >> typeCreationOrder [ 
^394
]

{ #category : #'as yet unclassified' }
Turtlebot_actionsFindFiducialFeedback >> initialize [
	super initialize.

]
