Class {
	#name : #OCNMacOSXPosixLibraryOCNUdpSocketReceivingDataTest,
	#superclass : #OCNUdpSocketReceivingDataTest,
	#category : #'Ocean-Tests-Generated-OCNMacOSXPosixLibrary'
}

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNUdpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNUdpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNMacOSXPosixLibrary
]
