Class {
	#name : #OCNMacOSXPosixLibraryOCNTcpSocketSendingDataTest,
	#superclass : #OCNTcpSocketSendingDataTest,
	#category : #'Ocean-Tests-Generated-OCNMacOSXPosixLibrary'
}

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNTcpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNTcpSocketSendingDataTest >> networkLibraryClass [ 
^OCNMacOSXPosixLibrary
]
