Class {
	#name : #OCNMacOSXPosixLibraryOCNTcpSocketReceivingDataTest,
	#superclass : #OCNTcpSocketReceivingDataTest,
	#category : #'Ocean-Tests-Generated-OCNMacOSXPosixLibrary'
}

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNTcpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNTcpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNMacOSXPosixLibrary
]
