Class {
	#name : #OCNMacOSXPosixLibraryOCNUdpSocketSendingDataTest,
	#superclass : #OCNUdpSocketSendingDataTest,
	#category : #'Ocean-Tests-Generated-OCNMacOSXPosixLibrary'
}

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNUdpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNMacOSXPosixLibraryOCNUdpSocketSendingDataTest >> networkLibraryClass [ 
^OCNMacOSXPosixLibrary
]
