Class {
	#name : #OCNSocketPluginLibraryOCNUdpSocketSendingDataTest,
	#superclass : #OCNUdpSocketSendingDataTest,
	#category : #'Ocean-Tests-Generated-OCNSocketPluginLibrary'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketSendingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
