Class {
	#name : #OCNSocketPluginLibraryOCNTcpSocketSendingDataTest,
	#superclass : #OCNTcpSocketSendingDataTest,
	#category : #'Ocean-Libraries-Plugin-Tests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketSendingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
