Class {
	#name : #OCNSocketPluginLibraryOCNUdpSocketReceivingDataTest,
	#superclass : #OCNUdpSocketReceivingDataTest,
	#category : #'Ocean-Libraries-Plugin-Tests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
