"
# PhaROS
	## What is PhaROS? 
		PhaROS is a framework for Robot Operative System that provides a powerful environment to:
		
		1- Develop ROS nodes in a powertful object oriented ambient.
		2- Manage ROS system, from node dependencies in runtime to message deployment, using a programming environment.
		3- Define repetable and testeable experiments
		
	
	
"
Class {
	#name : #PhaROSManifest,
	#superclass : #Object,
	#category : #PhaROS
}
