Class {
	#name : #PhaROSStaticPackage,
	#superclass : #PhaROSPackage,
	#category : #'PhaROS-Packages'
}

{ #category : #'as yet unclassified' }
PhaROSStaticPackage class >> dependencies [
	^ {}
]

{ #category : #'as yet unclassified' }
PhaROSStaticPackage class >> types [
	^ {}
]

{ #category : #'as yet unclassified' }
PhaROSStaticPackage >> dependencies [
	^ self class dependencies.
]

{ #category : #'as yet unclassified' }
PhaROSStaticPackage >> types [
	^ self class types.
]
