Class {
	#name : #ROBEmployee,
	#superclass : #Object,
	#instVars : [
		'name',
		'office',
		'titles',
		'charge',
		'work'
	],
	#category : #'RoboShop-Lab-Places'
}

{ #category : #'as yet unclassified' }
ROBEmployee class >> AlbanGUINARD [ 
	^  ROBEmployee new charge: 'chef de projets'; name: 'Alban GUINARD' ; titles: ''; work: '' 
]

{ #category : #employees }
ROBEmployee class >> AnthonyFLEURY [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Anthony FLEURY' ; titles: 'Anthony FLEURY ; Anthony ; FLEURY ; Doctor ; PhD'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> AntoineCHAMMAS [ 
	^  ROBEmployee new charge: 'PhD. Student'; name: 'Antoine CHAMMAS' ; titles: 'Antoine CHAMMAS ; Antoine ; CHAMMAS '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> AntoineSYLVAIN [ 
	^  ROBEmployee new charge: 'PhD. Student'; name: 'Antoine SYLVAIN' ; titles: 'Antoine SYLVAIN ; Antoine ; SYLVAIN'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> ArnaudDONIEC [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Arnaud DONIEC' ; titles: 'Arnaud DONIEC; Arnaud ; DONIEC ; Doctor ; PhD'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> BlaiseGUEPIE [ 
	^  ROBEmployee new charge: 'Post-DOC'; name: 'Blaise GUEPIE' ; titles: 'Blaise GUEPIE ; Blaise; GUEPIE'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> CecileLABARRE [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Cecile LABARRE' ; titles: 'Cecile LABARRE ; Cecile ; LABARRE ; Doctor ; PhD'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> ChristineDELILLE [ 
	^  ROBEmployee new charge: 'Secretariat'; name: 'Christine DELILLE' ; titles: 'Christine DELILLE ; Christine ; DELILLE '; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> ChristinePETIIT [ 
	^  ROBEmployee new charge: 'chef de projets'; name: 'Christine PETIIT' ; titles: ''; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> DidierRYCKBOSH [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Didier RYCKBOSH' ; titles: 'Didier RYCKBOSH'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> EricDUVIELLA [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Eric DUVIELLA' ; titles: 'Eric DUVIELLA ; Eric ; DUVIELLA '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> FrancoisCORTE [ 
	^  ROBEmployee new charge: 'Technicien'; name: 'Francois CORTE' ; titles: 'Francois CORTE; Francois ; CORTE'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> FrankTEMPET [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Frank TEMPET' ; titles: ''; work: '' 
]

{ #category : #employees }
ROBEmployee class >> FredericKLOPCIC [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Frederic KLOPCIC' ; titles: 'Frederic KLOPCIC ; Frederic ; KLOPCIC ; Doctor ; PhD'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> GabrielHOUSSAYE [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Gabriel HOUSSAYE' ; titles: 'Gabriel HOUSSAYE; Gabriel ;HOUSSAYE; Doctor ; PhD'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> GuillermoPOLITO [ 
	^  ROBEmployee new charge: 'PhD. Student'; name: 'Guillermo POLITO' ; titles: 'Guillermo POLITO; Guillermo ; POLITO'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> HenriDELEPLANQUE [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Henri DELEPLANQUE' ; titles: 'Henri DELEPLANQUE ; Henri  ; DELEPLANQUE  '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> HouariTOUBAKH [ 
	^  ROBEmployee new charge: 'PhD. Student'; name: 'Houari TOUBAKH' ; titles: 'Houari TOUBAKH; Houari ; TOUBAKH '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> InesYanyunLU [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Ines Yanyun LU' ; titles: 'Ines Yanyun LU ; Ines ; Yanyun ; LU '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> JacquesBOONAERT [ 
	^  ROBEmployee new charge: 'Adjoint, Charge de l enseignement productique '; name: 'Jacques BOONAERT' ; titles: 'Jacques BOONAERT;Jacques ; BOONAERT'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> JannikLAVAL [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Jannik LAVAL' ; titles: 'Jannik Laval ; Jannik ; Laval  '; work: '' 
]

{ #category : #employees }
ROBEmployee class >> KlaudiaHORVATH [ 
	^  ROBEmployee new charge: 'Post-DOC'; name: 'Klaudia HORVATH' ; titles: 'Klaudia ; Doctor Klaudia ; Doctor Horvath ; Klaudia Horvath ; Doctor KlaudiaHorvath'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> LalaRAJAOARISOA [ 
	^  ROBEmployee new charge: 'Ingeneur de recherche'; name: 'Lala RAJAOARISOA' ; titles: 'Lala RAJAOARISOA;Lala ;RAJAOARISOA'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> LucFABRESSE [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Luc FABRESSE' ; titles: 'Luc FABRESSE ;   '; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> MariePierLEROY [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Marie Pier LEROY' ; titles: 'Marie Pier LEROY; Marie Pier ; LEROY'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> MihalyPETRECZKY [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Mihaly PETRECZKY' ; titles: ''; work: '' 
]

{ #category : #employees }
ROBEmployee class >> MoamarSAYEDMOUCHAWEH [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Moamar SAYED MOUCHAWEH' ; titles: 'Moamar SAYED MOUCHAWEH ; Moamar ; SAYED ; MOUCHAWEH'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> MurielMORGAN [ 
	^  ROBEmployee new charge: 'Gestionnaire Administrative'; name: 'Muriel MORGAN' ; titles: 'Muriel MORGAN; Muriel ; MORGAN'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> NickolaosPAPOULIAS [ 
	^  ROBEmployee new charge: 'PhD. Student'; name: 'Nickolaos PAPOULIAS' ; titles: 'Nickolaos PAPOULIAS; Nickolaos ; PAPOULIAS'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> NouryBOURAQADI [ 
	^  ROBEmployee new charge: 'Enseignant - chercheur'; name: 'Noury BOURAQADI' ; titles: 'Noury BOURAQUADI ; Nourradine ; Noury ; BOURAQUADI'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> PhilippeHASBROUCQ [ 
	^  ROBEmployee new charge: 'Chef du Department'; name: 'Philippe HASBROUCQ' ; titles: 'Philippe HASBROUCQ; Philippe ; HASBROUCQ; Chef ; '; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> SandrineREIGUEZ [ 
	^  ROBEmployee new charge: 'Technicien'; name: 'Sandrine REIGUEZ' ; titles: 'Sandrine REIGUEZ;Sandrine ;REIGUEZ'; work: '' 
]

{ #category : #employees }
ROBEmployee class >> SantiagoBRAGAGNOLO [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Santiago BRAGAGNOLO' ; titles: 'Santiago BRAGAGNOLO ; Santiago ; BRAGAGNOLO'; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> SebastienAMBELLOUIS [ 
	^  ROBEmployee new charge: 'Charge de recherche IFSTTAR'; name: 'Sebastien AMBELLOUIS' ; titles: ''; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> StephaneLECOEUCHE [ 
	^  ROBEmployee new charge: 'Charge de la recherche'; name: 'Stephane LECOEUCHE' ; titles: ''; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> VincentLECOCQ [ 
	^  ROBEmployee new charge: 'Ingenieur'; name: 'Vincent LECOCQ' ; titles: ''; work: '' 
]

{ #category : #'as yet unclassified' }
ROBEmployee class >> VuTuanHieuLE [ 
	^  ROBEmployee new charge: ''; name: 'Vu Tuan Hieu LE' ; titles: ''; work: '' 
]

{ #category : #employees }
ROBEmployee class >> ZhiYAN [ 
	^  ROBEmployee new charge: 'Post-DOC '; name: 'Zhi YAN' ; titles: 'Zhi YAN; Zhi ; YAN'; work: '' 
]

{ #category : #accessing }
ROBEmployee >> asDump [
	| emp |

	emp :=  ' {1} new charge: ''{2}''; name: ''{3}''; titles: ''{4}''; work: ''{5}'' ' format:  {self class name.  charge . name . titles . work }.
	
	ROBEmployee class compile:( ' {1} 
	^ {2}' format: {name copyReplaceAll: ' ' with: '' . emp}).
	
	^ ' ROBEmployee {1} ' format: {name copyReplaceAll: ' ' with: '' }
]

{ #category : #accessing }
ROBEmployee >> charge [
	
	^ charge
]

{ #category : #accessing }
ROBEmployee >> charge: aString [
	
	charge := aString
]

{ #category : #accessing }
ROBEmployee >> image [
	| fileName |
	fileName :=  name copyReplaceAll: ' ' with: ''.
	fileName := fileName, 'Jpg'.
	^ ROBFileLibrary /fileName asSymbol.
]

{ #category : #accessing }
ROBEmployee >> name: aString [
	
	name := aString
]

{ #category : #accessing }
ROBEmployee >> office [
	
	^ office
]

{ #category : #accessing }
ROBEmployee >> office: anOffice [
	office := anOffice.
]

{ #category : #accessing }
ROBEmployee >> printOn: aStream [
	name printOn: aStream
]

{ #category : #accessing }
ROBEmployee >> titles [
	
	^ titles
]

{ #category : #accessing }
ROBEmployee >> titles: aString [
	
	titles := aString
]

{ #category : #accessing }
ROBEmployee >> work [
	
	^ work
]

{ #category : #accessing }
ROBEmployee >> work: aString [
	
	work := aString
]
