Class {
	#name : #ROBUniquePose,
	#superclass : #Object,
	#instVars : [
		'id',
		'point',
		'orientation'
	],
	#category : #'RoboShop-Lab-Places'
}

{ #category : #points }
ROBUniquePose class >> point1 [ 
	^  ROBUniquePose point: ((-5.535@0.37570000000000003)) orientation: 1.5401 id: 1
]

{ #category : #points }
ROBUniquePose class >> point10 [ 
	^  ROBUniquePose point: ((-1.173@ -24.840700000000002)) orientation: -0.9472 id: 10
]

{ #category : #points }
ROBUniquePose class >> point11 [ 
	^  ROBUniquePose point: ((-2.787@ -25.1441)) orientation: -0.8189000000000001 id: 11
]

{ #category : #points }
ROBUniquePose class >> point12 [ 
	^  ROBUniquePose point: ((-7.3500000000000005@ -29.2821)) orientation: -1.1793 id: 12
]

{ #category : #points }
ROBUniquePose class >> point13 [ 
	^  ROBUniquePose point: ((-8.218@ -30.2638)) orientation: -3.1249000000000002 id: 13
]

{ #category : #points }
ROBUniquePose class >> point14 [ 
	^  ROBUniquePose point: ((-8.27@ -32.1255)) orientation: 3.093 id: 14
]

{ #category : #points }
ROBUniquePose class >> point15 [ 
	^  ROBUniquePose point: ((-8.182@ -35.1878)) orientation: -0.13240000000000002 id: 15
]

{ #category : #points }
ROBUniquePose class >> point16 [ 
	^  ROBUniquePose point: ((-8.364@ -36.7016)) orientation: 3.0789 id: 16
]

{ #category : #points }
ROBUniquePose class >> point17 [ 
	^  ROBUniquePose point: ((-8.381@ -37.9609)) orientation: -3.0702000000000003 id: 17
]

{ #category : #points }
ROBUniquePose class >> point18 [ 
	^  ROBUniquePose point: ((-8.444@ -41.3251)) orientation: 3.0483000000000002 id: 18
]

{ #category : #points }
ROBUniquePose class >> point19 [ 
	^  ROBUniquePose point: ((-8.465@ -43.971900000000005)) orientation: 0.0367 id: 19
]

{ #category : #points }
ROBUniquePose class >> point2 [ 
	^  ROBUniquePose point: ((-2.588@ -0.038400000000000004)) orientation: -1.6426 id: 2
]

{ #category : #points }
ROBUniquePose class >> point20 [ 
	^  ROBUniquePose point: ((-8.512@ -45.867000000000004)) orientation: -0.09280000000000001 id: 20
]

{ #category : #points }
ROBUniquePose class >> point21 [ 
	^  ROBUniquePose point: ((-8.697000000000001@ -45.937400000000004)) orientation: 3.0515000000000003 id: 21
]

{ #category : #points }
ROBUniquePose class >> point22 [ 
	^  ROBUniquePose point: ((-1.54@ -49.2066)) orientation: 0.0238 id: 22
]

{ #category : #points }
ROBUniquePose class >> point23 [ 
	^  ROBUniquePose point: ((-6.203@ -23.0306)) orientation: 3.045 id: 23
]

{ #category : #points }
ROBUniquePose class >> point24 [ 
	^  ROBUniquePose point: ((-5.506@ -17.867900000000002)) orientation: -0.1333 id: 24
]

{ #category : #points }
ROBUniquePose class >> point25 [ 
	^  ROBUniquePose point: ((-4.708@ -15.108400000000001)) orientation: -0.1442 id: 25
]

{ #category : #points }
ROBUniquePose class >> point26 [ 
	^  ROBUniquePose point: ((-7.534@ -14.795200000000001)) orientation: -2.4184 id: 26
]

{ #category : #points }
ROBUniquePose class >> point27 [ 
	^  ROBUniquePose point: ((-6.916@ -15.4106)) orientation: -2.4292000000000002 id: 27
]

{ #category : #points }
ROBUniquePose class >> point28 [ 
	^  ROBUniquePose point: ((-6.916@ -15.4106)) orientation: -2.4292000000000002 id: 28
]

{ #category : #points }
ROBUniquePose class >> point29 [ 
	^  ROBUniquePose point: ((-7.266@ -4.8585)) orientation: -3.1267 id: 29
]

{ #category : #points }
ROBUniquePose class >> point3 [ 
	^  ROBUniquePose point: ((-1.53@0.1836)) orientation: 1.5188000000000001 id: 3
]

{ #category : #points }
ROBUniquePose class >> point30 [ 
	^  ROBUniquePose point: ((-7.104@1.2035)) orientation: 3.1271 id: 30
]

{ #category : #points }
ROBUniquePose class >> point31 [ 
	^  ROBUniquePose point: ((-7.014@2.4237)) orientation: -3.0921000000000003 id: 31
]

{ #category : #points }
ROBUniquePose class >> point32 [ 
	^  ROBUniquePose point: ((-6.766@7.202800000000001)) orientation: 3.1403000000000003 id: 32
]

{ #category : #points }
ROBUniquePose class >> point33 [ 
	^  ROBUniquePose point: ((-6.746@7.2129)) orientation: -0.0344 id: 33
]

{ #category : #points }
ROBUniquePose class >> point34 [ 
	^  ROBUniquePose point: ((-6.572@13.222100000000001)) orientation: -3.0964 id: 34
]

{ #category : #points }
ROBUniquePose class >> point35 [ 
	^  ROBUniquePose point: ((-6.625@14.157900000000001)) orientation: 3.1274 id: 35
]

{ #category : #points }
ROBUniquePose class >> point36 [ 
	^  ROBUniquePose point: ((-6.48@14.985600000000002)) orientation: 0.0405 id: 36
]

{ #category : #points }
ROBUniquePose class >> point37 [ 
	^  ROBUniquePose point: ((-6.496@18.9706)) orientation: -3.1105 id: 37
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point38 [ 
	^  ROBUniquePose point: ((4.8500000000000005@2.6162)) orientation: 1.6733 id: 38
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point39 [ 
	^  ROBUniquePose point: ((4.828@6.397)) orientation: 2.1741 id: 39
]

{ #category : #points }
ROBUniquePose class >> point4 [ 
	^  ROBUniquePose point: ((-1.613@ -0.0019)) orientation: -1.631 id: 4
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point40 [ 
	^  ROBUniquePose point: ((4.657@5.4175)) orientation: -3.1366 id: 40
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point41 [ 
	^  ROBUniquePose point: ((5.0760000000000005@6.58)) orientation: -0.0039000000000000003 id: 41
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point42 [ 
	^  ROBUniquePose point: ((5.165@7.9054)) orientation: -0.0451 id: 42
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point43 [ 
	^  ROBUniquePose point: ((5.102@12.5725)) orientation: -0.1315 id: 43
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point44 [ 
	^  ROBUniquePose point: ((5.192@13.9222)) orientation: -0.040400000000000005 id: 44
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point45 [ 
	^  ROBUniquePose point: ((5.543@18.7511)) orientation: 0.0274 id: 45
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point46 [ 
	^  ROBUniquePose point: ((5.6080000000000005@19.621100000000002)) orientation: -0.0649 id: 46
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point47 [ 
	^  ROBUniquePose point: ((4.359@20.500600000000002)) orientation: -2.4244000000000003 id: 47
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point48 [ 
	^  ROBUniquePose point: ((6.569@22.2479)) orientation: 0.4958 id: 48
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point49 [ 
	^  ROBUniquePose point: ((5.925@22.4072)) orientation: 1.8507 id: 49
]

{ #category : #points }
ROBUniquePose class >> point5 [ 
	^  ROBUniquePose point: ((-0.065@0.1854)) orientation: 1.48 id: 5
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point50 [ 
	^  ROBUniquePose point: ((4.098@21.6221)) orientation: 1.7286000000000001 id: 50
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point51 [ 
	^  ROBUniquePose point: ((-1.868@21.264300000000002)) orientation: 1.5070000000000001 id: 51
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point52 [ 
	^  ROBUniquePose point: ((-3.168@21.5412)) orientation: 1.3081 id: 52
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point53 [ 
	^  ROBUniquePose point: ((-6.206@25.9026)) orientation: -3.1251 id: 53
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point54 [ 
	^  ROBUniquePose point: ((-6.426@25.0131)) orientation: 3.1043000000000003 id: 54
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point55 [ 
	^  ROBUniquePose point: ((-6.558@20.4111)) orientation: -3.0943 id: 55
]

{ #category : #'as yet unclassified' }
ROBUniquePose class >> point56 [ 
	^  ROBUniquePose point: ((4.413@ -11.3667)) orientation: 0.0001 id: 56
]

{ #category : #points }
ROBUniquePose class >> point57 [ 
	^  ROBUniquePose point: ((4.011@ -8.2592000000000003)) orientation: -0.1198 id: 57
]

{ #category : #points }
ROBUniquePose class >> point6 [ 
	^  ROBUniquePose point: ((4.726@ -1.1745)) orientation: -0.0442 id: 6
]

{ #category : #points }
ROBUniquePose class >> point7 [ 
	^  ROBUniquePose point: ((5.011@ -2.2592000000000003)) orientation: -0.1198 id: 7
]

{ #category : #points }
ROBUniquePose class >> point8 [ 
	^  ROBUniquePose point: ((5.011@ -2.2592)) orientation: -0.1198 id: 8
]

{ #category : #points }
ROBUniquePose class >> point9 [ 
	^  ROBUniquePose point: ((4.316@ -15.744100000000001)) orientation: -0.24780000000000002 id: 9
]

{ #category : #constructor }
ROBUniquePose class >> point: aPoint orientation: anOrientation id: anID [
	^ self new point: aPoint; orientation: anOrientation; id: anID; yourself.
]

{ #category : #'as yet unclassified' }
ROBUniquePose >> asDump [
 	| dmp |
	
	dmp := ' ROBUniquePose point: ({1}) orientation: {2} id: {3}' format: { ((point at: #x)roundUpTo: 0.001) @ ((point at:#y) roundUpTo: 0.0001). (orientation at:#z)roundUpTo: 0.0001 . id }.
	ROBUniquePose class compile: (' point{1} 
	^ {2}' format: { id asString . dmp }).
	^ ' ROBUniquePose point{1}' format: { id asString }
]

{ #category : #accessing }
ROBUniquePose >> id [
	^ id
]

{ #category : #'as yet unclassified' }
ROBUniquePose >> id: anID [
	id := anID.
	
]

{ #category : #accessing }
ROBUniquePose >> orientation [
	^ orientation
]

{ #category : #'as yet unclassified' }
ROBUniquePose >> orientation: anOrientation [
	orientation := anOrientation
]

{ #category : #accessing }
ROBUniquePose >> point [
	^ point
]

{ #category : #'as yet unclassified' }
ROBUniquePose >> point: aPoint [
	point := aPoint
]
