Class {
	#name : #Ideas,
	#superclass : #Object,
	#category : #TaskIT
}

{ #category : #'as yet unclassified' }
Ideas >> ideas [
"
	
	
	
	
	TKTProcess para tratar polimorficamente procesos de pharo, procesamiento en el mismo thread, os processess, etc.
	
	
	

	WorkerDispatcher add: [
		channel peek.
		channel pick.
		
		channel put: something. 
	]. 

(
	[
		something
	] with: [
		something
	]
	) andThen: [
		
	].


	[ ] whenTrue: [ something ].



"
]
