Class {
	#name : #OCNSocketPluginLibraryOCNTcpSocketFailureTest,
	#superclass : #OCNTcpSocketFailureTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketFailureTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketFailureTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
