Class {
	#name : #OCNSocketPluginLibraryOCNTcpSocketReceivingDataTest,
	#superclass : #OCNTcpSocketReceivingDataTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
