Class {
	#name : #OCNSocketPluginLibraryOCNTcpSocketFinalizationTest,
	#superclass : #OCNTcpSocketFinalizationTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketFinalizationTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNTcpSocketFinalizationTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
