Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketReceivingDataTest,
	#superclass : #OCNSocketPluginLibraryOCNUdpSocketReceivingDataTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
