Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketSendingDataTest,
	#superclass : #OCNSocketPluginLibraryOCNUdpSocketSendingDataTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNUdpSocketSendingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
