Class {
	#name : #OCNSocketPluginLibraryOCNUdpSocketFinalizationTest,
	#superclass : #OCNUdpSocketFinalizationTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketFinalizationTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNUdpSocketFinalizationTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
