Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketFailureTest,
	#superclass : #OCNSocketPluginLibraryOCNTcpSocketFailureTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketFailureTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketFailureTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
