Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketReceivingDataTest,
	#superclass : #OCNSocketPluginLibraryOCNTcpSocketReceivingDataTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketReceivingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketReceivingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
