Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketSendingDataTest,
	#superclass : #OCNSocketPluginLibraryOCNTcpSocketSendingDataTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketSendingDataTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketSendingDataTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
