Class {
	#name : #OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketTest,
	#superclass : #OCNSocketPluginLibraryOCNTcpSocketTest,
	#category : #'Ocean-LibraryPluginTests-Generated'
}

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketTest class >> isAbstract [ 
^false
]

{ #category : #'as yet unclassified' }
OCNSocketPluginLibraryOCNSocketPluginLibraryOCNTcpSocketTest >> networkLibraryClass [ 
^OCNSocketPluginLibrary
]
